// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAItCobAjqyVI_DW452nhQzghbNKWR6UvE',
    appId: '1:322230562387:web:4b29f16832f538e18460a6',
    messagingSenderId: '322230562387',
    projectId: 'vertretungsplan-5aa7e',
    authDomain: 'vertretungsplan-5aa7e.firebaseapp.com',
    storageBucket: 'vertretungsplan-5aa7e.firebasestorage.app',
    measurementId: 'G-11G4ZMNJ7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE6k6k7wUn89qjI-iGMJfKPhhdSbCDw6s',
    appId: '1:322230562387:android:142cda6f4d4d50d88460a6',
    messagingSenderId: '322230562387',
    projectId: 'vertretungsplan-5aa7e',
    storageBucket: 'vertretungsplan-5aa7e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANpbU7Fb91iwGRqsNu49IlWJ-lUemfVTc',
    appId: '1:322230562387:ios:4b588f3b45dca2428460a6',
    messagingSenderId: '322230562387',
    projectId: 'vertretungsplan-5aa7e',
    storageBucket: 'vertretungsplan-5aa7e.firebasestorage.app',
    iosBundleId: 'com.example.planner',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANpbU7Fb91iwGRqsNu49IlWJ-lUemfVTc',
    appId: '1:322230562387:ios:4b588f3b45dca2428460a6',
    messagingSenderId: '322230562387',
    projectId: 'vertretungsplan-5aa7e',
    storageBucket: 'vertretungsplan-5aa7e.firebasestorage.app',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAItCobAjqyVI_DW452nhQzghbNKWR6UvE',
    appId: '1:322230562387:web:3e07062d3376aaef8460a6',
    messagingSenderId: '322230562387',
    projectId: 'vertretungsplan-5aa7e',
    authDomain: 'vertretungsplan-5aa7e.firebaseapp.com',
    storageBucket: 'vertretungsplan-5aa7e.firebasestorage.app',
    measurementId: 'G-ECLY11JHJE',
  );
}
