const typeMap = {
  "eigenverantwortliches arbeiten": "Entfall",
  "veranst.": "Veranstaltung",
  "trotzabsenz": "Trotz Absenz",
  "sondereins.": "Sondereinsatz",
  "raum-vtr.": "Raum-Vertretung",
};

const subjectMap = {
  "d": "Deutsch",
  "f": "Französisch",
  "spa": "Spanisch",
  "lat": "Latein",
  "l": "Latein",
  "ph": "Physik",
  "ch": "Chemie",
  "bio": "Biologie",
  "powi": "PoWi",
  "m": "Mathematik",
  "ethi": "Ethik",
  "rka": "Reli Katholisch",
  "g": "Geschichte",
  "rev": "Reli Evangelisch",
  "spo": "Sport",
  "e": "Englisch",
  "ku": "Kunst",
  "tut": "Tutorenkurs",
  "chin": "Chinesisch",
  "info": "Informatik",
  "geo": "Erdkunde",
};
